server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:file:~/users
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console.enabled: true


